global using System.Text.Json.Serialization;
global using ChatGptInterlocutor.Models;
global using ChatGptInterlocutor.Services;
global using Flurl.Http;
global using MediatR;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Options;
global using Microsoft.OpenApi.Models;
global using Newtonsoft.Json;